---
title: "Finding Common Origins of Milky Way Stars"
date: today
author: "Andersen Chang$^*$, Tiffany M. Tang$^*$, Tarek M. Zikry$^*$, Genevera I. Allen"
format: html
---

## Introduction

The emergence of large spectroscopic surveys of the Milky Way has led to significant interest in studying the chemical origins of the Galaxy's formation.
In particular, researchers are often interested in understanding how stars were formed or evolved chemodynamically over large periods of time. 
To this end, previous work has shown that in the process of forming a stellar body, parent molecular clouds can produce hundreds of stars in a single burst [@krumholz2014star], but due to astronomical dynamics, these shared origins are challenging to find. 

In this case study, we will leverage the Apache Point Observatory Galactic Evolution Experiment (APOGEE) DR17 [@prieto2008apogee], a large high-resolution spectroscopic survey of stars compring the disk (i.e., the primary area of the Milky Way's stellar mass), in order to identify groups of stars in the Milky Way with similar chemical properties and gain insights into the shared origins of stars that were formed together.

## Outline

In what follows, we will walk through a typical unsupervised machine learning workflow for scientific discovery, namely, to identify common origins of stars in the Milky Way. To this end, we will proceed through the following steps:

- [**Data Preparation and Cleaning**](./notebooks/01-astro-case-study-data.html):
We begin by loading in the data, performing some basic quality control filtering and cleaning, and splitting the data into a training and test set.
- [**Exploratory Data Analysis**](./notebooks/02-astro-case-study-eda.html): 
We then conduct a brief exploratory data analysis to better understand various characteristics of the data.
- [**Dimension Reduction**](./notebooks/03-astro-case-study-dimension-reduction.html): 
We further implement various dimension reduction techniques (and tune their hyperparameters) to both visualize the data in a lower-dimensional space and to prepare for clustering.
- [**Clustering (training)**](./notebooks/04-astro-case-study-clustering-train.html): 
Next, we fit various clustering techniques on multiple *versions* of the training data (e.g., using different ways of preparing the data) and perform model selection and hyperparameter tuning based upon the stability of the resulting clusters.
- [**Clustering (validation)**](./notebooks/05-astro-case-study-clustering-validation.html): 
We then validate the clustering results on the test set (e.g., via generalizability metrics and its stability across alternative data preprocessing pipelines).
- [**Interpretation of Clustering Results**](./notebooks/06-astro-case-study-interpret.html): 
Finally, we re-fit the best clustering pipeline on the full data and interpret the final clusters in the context of the scientific question at hand.
